name: Release

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SITE_TITLE: ${{ secrets.SITE_TITLE }}
      SITE_LANGUAGE_CODE: ${{ secrets.SITE_LANGUAGE_CODE }}
      SITE_BASEURL: ${{ secrets.SITE_BASEURL }}
      DOMAIN: ${{ secrets.DOMAIN }}
      HUGO_ENV: ${{ secrets.HUGO_ENV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build site
        run: make build

      - name: Store site as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: Site
          if-no-files-found: error
          path: app/public/**/*

      - name: Initialize terraform
        if: ${{ env.AWS_ACCESS_KEY_ID != '' }}
        run: make terraform-init
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
